# Development environment overrides

image:
  tag: "latest"

replicaCount: 1

env:
  - name: VERSION
    value: "dev"
  - name: COLOR
    value: "#28a745" # Green for dev

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
