# Test environment overrides
# NOTE: Add Chart.yaml to this folder to enable deployment

service-chart:
  app:
    replicaCount: 1

  configEnv:
    pairs:
      VERSION: "tst"
      COLOR: "#17a2b8" # Blue for test
