# Test environment overrides
# NOTE: Add Chart.yaml to this folder to enable deployment

image:
  tag: "latest"

replicaCount: 1

env:
  - name: VERSION
    value: "tst"
  - name: COLOR
    value: "#17a2b8" # Blue for test

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
