# Acceptance environment overrides
# NOTE: Add Chart.yaml to this folder to enable deployment

replicaCount: 1

env:
  - name: VERSION
    value: "acc"
  - name: COLOR
    value: "#ffc107" # Yellow for acceptance
