# Production environment overrides
# NOTE: Add Chart.yaml to this folder to enable deployment

replicaCount: 2

env:
  - name: VERSION
    value: "prd"
  - name: COLOR
    value: "#dc3545" # Red for production

